name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install go1.20rc1
      run: |
        go install golang.org/dl/go1.20rc1@latest
        go1.20rc1 download

    - name: Build
      run: go1.20rc1 build -v ./...

    - name: Test
      run: go1.20rc1 test -v ./...
