name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      run: |
        curl -OL https://go.dev/dl/go1.20rc1.linux-amd64.tar.gz
        tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
